### ISSUE TITLE
Research projects to see how similar tools have been implemented

### ISSUE THREAD

**Issue by AlexGaiser** [AlexGaiser/fast-react#2]
We should be looking for

- clever / interesting implementations of this concept
- repositories with clear documentation/code
- projects with active development so we can ask the repo owner for advice or help
- tools that others have used to make development of **our project** easier

Currently, I have been searching NPM for the most popular react project scaffolding/CLI tools.

Here is a list of projects I have that are useful:
- [create-new-app](https://github.com/qodesmith/create-new-app) (this one is fully featured and fairly active)
- [lean-react-app](https://github.com/pawlo0/lean-react-app)
- [create-fullstack-app](https://github.com/Divlo/create-fullstack-app) (very up to date, more features than we need but has an interesting implementation)

Once we are satisfied we have a good understanding of how other projects have approached this topic, we should move on to issue #4

**Comment by Scott-Ian** [comment]
Just wanted to give a shoutout to create-new-app, as I really like the implementation from a UX perspective. Super easy, simple console queries to prompt the user for what to include in the app creation. 

I think that project could use better documentation though. Treating users or potential users as if they know almost nothing would be better. 

Honestly, really into CNA, and want to emulate a lot from that project.
